---
- name: This playbook install httpd
  hosts: all
  become: true
  tasks:
  - name: install packages
    yum:
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"
    
  - name: start httpd service
    service:
     name: httpd
     state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: install packages
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: Start service apache2, if not started
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"
  
  - name: copy index.html
    copy:
     src: /opt/ansible/index.html
     dest: /var/www/html
     mode: 0666
