---
- name: This playbook install packages
  hosts: webservers
  become: true
  tasks:
  - name: install packages
    yum:
      # name: ['git', 'make', 'gcc', 'wget', 'telnet', 'gzip']
      name: "{{ item }}"
      state: installed
    with_items:
     - git
     - make
     - gcc
     - wget
     - telnet
     - gzip
