---
- name: This playbook install httpd
  hosts: webservers
  become: true
  tasks:
  - name: install packages
    yum:
     name: httpd
     state: installed
    notify: start httpd service
  
  handlers:
  - name: start httpd service
    ansible.builtin.service:
     name: httpd
     state: started 
