---
- name: setup Tomcat
  hosts: all
  become: true
  tasks:
  - name: Install Java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  
  - name: Install Java on Ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  
  - name: download tomcat packages
    get_url:
      url: https://apachemirror.sg.wuchna.com/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.tar.gz
      dest: /opt
  
  - name: untar the apache packages
    unarchive:
      src: /opt/apache-tomcat-8.5.66.tar.gz
      dest: /opt
      remote_src: yes

  - name: add execution permission on startup.sh file
    file:
      path: /opt/apache-tomcat-8.5.66/bin/startup.sh
      mode: 0777
  
  - name: Start Tomcat services
    shell: nohup ./startup.sh
    args:
        chdir: /opt/apache-tomcat-8.5.66/bin/
